// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: proto/challenge.proto

package challenge

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           int64                  `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Note          string                 `protobuf:"bytes,2,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_proto_challenge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_challenge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_challenge_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *PingRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pong          string                 `protobuf:"bytes,1,opt,name=pong,proto3" json:"pong,omitempty"`
	Ts            int64                  `protobuf:"varint,2,opt,name=ts,proto3" json:"ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_proto_challenge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_challenge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_challenge_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetPong() string {
	if x != nil {
		return x.Pong
	}
	return ""
}

func (x *PingResponse) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

type PublicInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Q             string                 `protobuf:"bytes,3,opt,name=q,proto3" json:"q,omitempty"`
	Page          int32                  `protobuf:"varint,7,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicInfoRequest) Reset() {
	*x = PublicInfoRequest{}
	mi := &file_proto_challenge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicInfoRequest) ProtoMessage() {}

func (x *PublicInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_challenge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicInfoRequest.ProtoReflect.Descriptor instead.
func (*PublicInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_challenge_proto_rawDescGZIP(), []int{2}
}

func (x *PublicInfoRequest) GetQ() string {
	if x != nil {
		return x.Q
	}
	return ""
}

func (x *PublicInfoRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type PublicInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []string               `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Meta          map[string]string      `protobuf:"bytes,10,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicInfoResponse) Reset() {
	*x = PublicInfoResponse{}
	mi := &file_proto_challenge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicInfoResponse) ProtoMessage() {}

func (x *PublicInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_challenge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicInfoResponse.ProtoReflect.Descriptor instead.
func (*PublicInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_challenge_proto_rawDescGZIP(), []int{3}
}

func (x *PublicInfoResponse) GetEntries() []string {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *PublicInfoResponse) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

type ListRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Page    int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PerPage int32                  `protobuf:"varint,2,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	// Types that are valid to be assigned to Filter:
	//
	//	*ListRequest_ByTag
	//	*ListRequest_OwnerId
	Filter        isListRequest_Filter `protobuf_oneof:"filter"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_proto_challenge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_challenge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_proto_challenge_proto_rawDescGZIP(), []int{4}
}

func (x *ListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListRequest) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

func (x *ListRequest) GetFilter() isListRequest_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *ListRequest) GetByTag() string {
	if x != nil {
		if x, ok := x.Filter.(*ListRequest_ByTag); ok {
			return x.ByTag
		}
	}
	return ""
}

func (x *ListRequest) GetOwnerId() int64 {
	if x != nil {
		if x, ok := x.Filter.(*ListRequest_OwnerId); ok {
			return x.OwnerId
		}
	}
	return 0
}

type isListRequest_Filter interface {
	isListRequest_Filter()
}

type ListRequest_ByTag struct {
	ByTag string `protobuf:"bytes,10,opt,name=by_tag,json=byTag,proto3,oneof"`
}

type ListRequest_OwnerId struct {
	OwnerId int64 `protobuf:"varint,11,opt,name=owner_id,json=ownerId,proto3,oneof"`
}

func (*ListRequest_ByTag) isListRequest_Filter() {}

func (*ListRequest_OwnerId) isListRequest_Filter() {}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*DocSummary          `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_proto_challenge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_challenge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_proto_challenge_proto_rawDescGZIP(), []int{5}
}

func (x *ListResponse) GetItems() []*DocSummary {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type DocSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	CreatedUnix   int64                  `protobuf:"varint,50,opt,name=created_unix,json=createdUnix,proto3" json:"created_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocSummary) Reset() {
	*x = DocSummary{}
	mi := &file_proto_challenge_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocSummary) ProtoMessage() {}

func (x *DocSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_challenge_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocSummary.ProtoReflect.Descriptor instead.
func (*DocSummary) Descriptor() ([]byte, []int) {
	return file_proto_challenge_proto_rawDescGZIP(), []int{6}
}

func (x *DocSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DocSummary) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DocSummary) GetCreatedUnix() int64 {
	if x != nil {
		return x.CreatedUnix
	}
	return 0
}

type CreateDocRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	Owner         string                 `protobuf:"bytes,20,opt,name=owner,proto3" json:"owner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDocRequest) Reset() {
	*x = CreateDocRequest{}
	mi := &file_proto_challenge_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDocRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDocRequest) ProtoMessage() {}

func (x *CreateDocRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_challenge_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDocRequest.ProtoReflect.Descriptor instead.
func (*CreateDocRequest) Descriptor() ([]byte, []int) {
	return file_proto_challenge_proto_rawDescGZIP(), []int{7}
}

func (x *CreateDocRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateDocRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateDocRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreateDocRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

type UpdateDocRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*UpdateDocRequest_Content
	//	*UpdateDocRequest_Title
	Payload isUpdateDocRequest_Payload `protobuf_oneof:"payload"`
	// tags must be OUTSIDE the oneof because 'repeated' inside oneof is invalid, i mean... ok
	Tags          []string `protobuf:"bytes,12,rep,name=tags,proto3" json:"tags,omitempty"`
	Owner         string   `protobuf:"bytes,20,opt,name=owner,proto3" json:"owner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDocRequest) Reset() {
	*x = UpdateDocRequest{}
	mi := &file_proto_challenge_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDocRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDocRequest) ProtoMessage() {}

func (x *UpdateDocRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_challenge_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDocRequest.ProtoReflect.Descriptor instead.
func (*UpdateDocRequest) Descriptor() ([]byte, []int) {
	return file_proto_challenge_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateDocRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateDocRequest) GetPayload() isUpdateDocRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *UpdateDocRequest) GetContent() string {
	if x != nil {
		if x, ok := x.Payload.(*UpdateDocRequest_Content); ok {
			return x.Content
		}
	}
	return ""
}

func (x *UpdateDocRequest) GetTitle() string {
	if x != nil {
		if x, ok := x.Payload.(*UpdateDocRequest_Title); ok {
			return x.Title
		}
	}
	return ""
}

func (x *UpdateDocRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *UpdateDocRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

type isUpdateDocRequest_Payload interface {
	isUpdateDocRequest_Payload()
}

type UpdateDocRequest_Content struct {
	Content string `protobuf:"bytes,10,opt,name=content,proto3,oneof"`
}

type UpdateDocRequest_Title struct {
	Title string `protobuf:"bytes,11,opt,name=title,proto3,oneof"`
}

func (*UpdateDocRequest_Content) isUpdateDocRequest_Payload() {}

func (*UpdateDocRequest_Title) isUpdateDocRequest_Payload() {}

type DocResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocResponse) Reset() {
	*x = DocResponse{}
	mi := &file_proto_challenge_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocResponse) ProtoMessage() {}

func (x *DocResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_challenge_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocResponse.ProtoReflect.Descriptor instead.
func (*DocResponse) Descriptor() ([]byte, []int) {
	return file_proto_challenge_proto_rawDescGZIP(), []int{9}
}

func (x *DocResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DocResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Owner         string                 `protobuf:"bytes,20,opt,name=owner,proto3" json:"owner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_proto_challenge_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_challenge_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_challenge_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_proto_challenge_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_challenge_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_challenge_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

// these are the target endpoints
type GetSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretRequest) Reset() {
	*x = GetSecretRequest{}
	mi := &file_proto_challenge_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretRequest) ProtoMessage() {}

func (x *GetSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_challenge_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretRequest.ProtoReflect.Descriptor instead.
func (*GetSecretRequest) Descriptor() ([]byte, []int) {
	return file_proto_challenge_proto_rawDescGZIP(), []int{12}
}

func (x *GetSecretRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

type SecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secret        string                 `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	Created       int64                  `protobuf:"varint,20,opt,name=created,proto3" json:"created,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretResponse) Reset() {
	*x = SecretResponse{}
	mi := &file_proto_challenge_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretResponse) ProtoMessage() {}

func (x *SecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_challenge_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretResponse.ProtoReflect.Descriptor instead.
func (*SecretResponse) Descriptor() ([]byte, []int) {
	return file_proto_challenge_proto_rawDescGZIP(), []int{13}
}

func (x *SecretResponse) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *SecretResponse) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

// still noise here
type AdminListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Q             string                 `protobuf:"bytes,2,opt,name=q,proto3" json:"q,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminListRequest) Reset() {
	*x = AdminListRequest{}
	mi := &file_proto_challenge_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminListRequest) ProtoMessage() {}

func (x *AdminListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_challenge_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminListRequest.ProtoReflect.Descriptor instead.
func (*AdminListRequest) Descriptor() ([]byte, []int) {
	return file_proto_challenge_proto_rawDescGZIP(), []int{14}
}

func (x *AdminListRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *AdminListRequest) GetQ() string {
	if x != nil {
		return x.Q
	}
	return ""
}

type AdminListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdminItems    []string               `protobuf:"bytes,1,rep,name=admin_items,json=adminItems,proto3" json:"admin_items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminListResponse) Reset() {
	*x = AdminListResponse{}
	mi := &file_proto_challenge_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminListResponse) ProtoMessage() {}

func (x *AdminListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_challenge_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminListResponse.ProtoReflect.Descriptor instead.
func (*AdminListResponse) Descriptor() ([]byte, []int) {
	return file_proto_challenge_proto_rawDescGZIP(), []int{15}
}

func (x *AdminListResponse) GetAdminItems() []string {
	if x != nil {
		return x.AdminItems
	}
	return nil
}

type AdminAuditRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          int64                  `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	To            int64                  `protobuf:"varint,2,opt,name=to,proto3" json:"to,omitempty"`
	Types         []string               `protobuf:"bytes,10,rep,name=types,proto3" json:"types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminAuditRequest) Reset() {
	*x = AdminAuditRequest{}
	mi := &file_proto_challenge_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminAuditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminAuditRequest) ProtoMessage() {}

func (x *AdminAuditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_challenge_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminAuditRequest.ProtoReflect.Descriptor instead.
func (*AdminAuditRequest) Descriptor() ([]byte, []int) {
	return file_proto_challenge_proto_rawDescGZIP(), []int{16}
}

func (x *AdminAuditRequest) GetFrom() int64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *AdminAuditRequest) GetTo() int64 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *AdminAuditRequest) GetTypes() []string {
	if x != nil {
		return x.Types
	}
	return nil
}

type AdminAuditResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []string               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminAuditResponse) Reset() {
	*x = AdminAuditResponse{}
	mi := &file_proto_challenge_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminAuditResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminAuditResponse) ProtoMessage() {}

func (x *AdminAuditResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_challenge_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminAuditResponse.ProtoReflect.Descriptor instead.
func (*AdminAuditResponse) Descriptor() ([]byte, []int) {
	return file_proto_challenge_proto_rawDescGZIP(), []int{17}
}

func (x *AdminAuditResponse) GetEvents() []string {
	if x != nil {
		return x.Events
	}
	return nil
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_proto_challenge_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_challenge_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_challenge_proto_rawDescGZIP(), []int{18}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ExpiresIn     int64                  `protobuf:"varint,2,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_proto_challenge_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_challenge_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_proto_challenge_proto_rawDescGZIP(), []int{19}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResponse) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

var File_proto_challenge_proto protoreflect.FileDescriptor

const file_proto_challenge_proto_rawDesc = "" +
	"\n" +
	"\x15proto/challenge.proto\x12\tchallenge\"3\n" +
	"\vPingRequest\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x03R\x03seq\x12\x12\n" +
	"\x04note\x18\x02 \x01(\tR\x04note\"2\n" +
	"\fPingResponse\x12\x12\n" +
	"\x04pong\x18\x01 \x01(\tR\x04pong\x12\x0e\n" +
	"\x02ts\x18\x02 \x01(\x03R\x02ts\"5\n" +
	"\x11PublicInfoRequest\x12\f\n" +
	"\x01q\x18\x03 \x01(\tR\x01q\x12\x12\n" +
	"\x04page\x18\a \x01(\x05R\x04page\"\xa4\x01\n" +
	"\x12PublicInfoResponse\x12\x18\n" +
	"\aentries\x18\x01 \x03(\tR\aentries\x12;\n" +
	"\x04meta\x18\n" +
	" \x03(\v2'.challenge.PublicInfoResponse.MetaEntryR\x04meta\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"|\n" +
	"\vListRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x02 \x01(\x05R\aperPage\x12\x17\n" +
	"\x06by_tag\x18\n" +
	" \x01(\tH\x00R\x05byTag\x12\x1b\n" +
	"\bowner_id\x18\v \x01(\x03H\x00R\aownerIdB\b\n" +
	"\x06filter\"Q\n" +
	"\fListResponse\x12+\n" +
	"\x05items\x18\x01 \x03(\v2\x15.challenge.DocSummaryR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"U\n" +
	"\n" +
	"DocSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12!\n" +
	"\fcreated_unix\x182 \x01(\x03R\vcreatedUnix\"l\n" +
	"\x10CreateDocRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x12\x14\n" +
	"\x05owner\x18\x14 \x01(\tR\x05owner\"\x8b\x01\n" +
	"\x10UpdateDocRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\acontent\x18\n" +
	" \x01(\tH\x00R\acontent\x12\x16\n" +
	"\x05title\x18\v \x01(\tH\x00R\x05title\x12\x12\n" +
	"\x04tags\x18\f \x03(\tR\x04tags\x12\x14\n" +
	"\x05owner\x18\x14 \x01(\tR\x05ownerB\t\n" +
	"\apayload\"-\n" +
	"\vDocResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\"5\n" +
	"\rDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05owner\x18\x14 \x01(\tR\x05owner\" \n" +
	"\x0eDeleteResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"3\n" +
	"\x10GetSecretRequest\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\"B\n" +
	"\x0eSecretResponse\x12\x16\n" +
	"\x06secret\x18\x01 \x01(\tR\x06secret\x12\x18\n" +
	"\acreated\x18\x14 \x01(\x03R\acreated\"6\n" +
	"\x10AdminListRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\f\n" +
	"\x01q\x18\x02 \x01(\tR\x01q\"4\n" +
	"\x11AdminListResponse\x12\x1f\n" +
	"\vadmin_items\x18\x01 \x03(\tR\n" +
	"adminItems\"M\n" +
	"\x11AdminAuditRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\x03R\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\x03R\x02to\x12\x14\n" +
	"\x05types\x18\n" +
	" \x03(\tR\x05types\",\n" +
	"\x12AdminAuditResponse\x12\x16\n" +
	"\x06events\x18\x01 \x03(\tR\x06events\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"D\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x02 \x01(\x03R\texpiresIn2\xae\x05\n" +
	"\x0eSecretsService\x127\n" +
	"\x04Ping\x12\x16.challenge.PingRequest\x1a\x17.challenge.PingResponse\x12L\n" +
	"\rGetPublicInfo\x12\x1c.challenge.PublicInfoRequest\x1a\x1d.challenge.PublicInfoResponse\x12;\n" +
	"\bListDocs\x12\x16.challenge.ListRequest\x1a\x17.challenge.ListResponse\x12@\n" +
	"\tCreateDoc\x12\x1b.challenge.CreateDocRequest\x1a\x16.challenge.DocResponse\x12@\n" +
	"\tUpdateDoc\x12\x1b.challenge.UpdateDocRequest\x1a\x16.challenge.DocResponse\x12@\n" +
	"\tDeleteDoc\x12\x18.challenge.DeleteRequest\x1a\x19.challenge.DeleteResponse\x12C\n" +
	"\tGetSecret\x12\x1b.challenge.GetSecretRequest\x1a\x19.challenge.SecretResponse\x12F\n" +
	"\tAdminList\x12\x1b.challenge.AdminListRequest\x1a\x1c.challenge.AdminListResponse\x12I\n" +
	"\n" +
	"AdminAudit\x12\x1c.challenge.AdminAuditRequest\x1a\x1d.challenge.AdminAuditResponse\x12:\n" +
	"\x05Login\x12\x17.challenge.LoginRequest\x1a\x18.challenge.LoginResponseB\x1cZ\x1agrpc-chall/proto;challengeb\x06proto3"

var (
	file_proto_challenge_proto_rawDescOnce sync.Once
	file_proto_challenge_proto_rawDescData []byte
)

func file_proto_challenge_proto_rawDescGZIP() []byte {
	file_proto_challenge_proto_rawDescOnce.Do(func() {
		file_proto_challenge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_challenge_proto_rawDesc), len(file_proto_challenge_proto_rawDesc)))
	})
	return file_proto_challenge_proto_rawDescData
}

var file_proto_challenge_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_proto_challenge_proto_goTypes = []any{
	(*PingRequest)(nil),        // 0: challenge.PingRequest
	(*PingResponse)(nil),       // 1: challenge.PingResponse
	(*PublicInfoRequest)(nil),  // 2: challenge.PublicInfoRequest
	(*PublicInfoResponse)(nil), // 3: challenge.PublicInfoResponse
	(*ListRequest)(nil),        // 4: challenge.ListRequest
	(*ListResponse)(nil),       // 5: challenge.ListResponse
	(*DocSummary)(nil),         // 6: challenge.DocSummary
	(*CreateDocRequest)(nil),   // 7: challenge.CreateDocRequest
	(*UpdateDocRequest)(nil),   // 8: challenge.UpdateDocRequest
	(*DocResponse)(nil),        // 9: challenge.DocResponse
	(*DeleteRequest)(nil),      // 10: challenge.DeleteRequest
	(*DeleteResponse)(nil),     // 11: challenge.DeleteResponse
	(*GetSecretRequest)(nil),   // 12: challenge.GetSecretRequest
	(*SecretResponse)(nil),     // 13: challenge.SecretResponse
	(*AdminListRequest)(nil),   // 14: challenge.AdminListRequest
	(*AdminListResponse)(nil),  // 15: challenge.AdminListResponse
	(*AdminAuditRequest)(nil),  // 16: challenge.AdminAuditRequest
	(*AdminAuditResponse)(nil), // 17: challenge.AdminAuditResponse
	(*LoginRequest)(nil),       // 18: challenge.LoginRequest
	(*LoginResponse)(nil),      // 19: challenge.LoginResponse
	nil,                        // 20: challenge.PublicInfoResponse.MetaEntry
}
var file_proto_challenge_proto_depIdxs = []int32{
	20, // 0: challenge.PublicInfoResponse.meta:type_name -> challenge.PublicInfoResponse.MetaEntry
	6,  // 1: challenge.ListResponse.items:type_name -> challenge.DocSummary
	0,  // 2: challenge.SecretsService.Ping:input_type -> challenge.PingRequest
	2,  // 3: challenge.SecretsService.GetPublicInfo:input_type -> challenge.PublicInfoRequest
	4,  // 4: challenge.SecretsService.ListDocs:input_type -> challenge.ListRequest
	7,  // 5: challenge.SecretsService.CreateDoc:input_type -> challenge.CreateDocRequest
	8,  // 6: challenge.SecretsService.UpdateDoc:input_type -> challenge.UpdateDocRequest
	10, // 7: challenge.SecretsService.DeleteDoc:input_type -> challenge.DeleteRequest
	12, // 8: challenge.SecretsService.GetSecret:input_type -> challenge.GetSecretRequest
	14, // 9: challenge.SecretsService.AdminList:input_type -> challenge.AdminListRequest
	16, // 10: challenge.SecretsService.AdminAudit:input_type -> challenge.AdminAuditRequest
	18, // 11: challenge.SecretsService.Login:input_type -> challenge.LoginRequest
	1,  // 12: challenge.SecretsService.Ping:output_type -> challenge.PingResponse
	3,  // 13: challenge.SecretsService.GetPublicInfo:output_type -> challenge.PublicInfoResponse
	5,  // 14: challenge.SecretsService.ListDocs:output_type -> challenge.ListResponse
	9,  // 15: challenge.SecretsService.CreateDoc:output_type -> challenge.DocResponse
	9,  // 16: challenge.SecretsService.UpdateDoc:output_type -> challenge.DocResponse
	11, // 17: challenge.SecretsService.DeleteDoc:output_type -> challenge.DeleteResponse
	13, // 18: challenge.SecretsService.GetSecret:output_type -> challenge.SecretResponse
	15, // 19: challenge.SecretsService.AdminList:output_type -> challenge.AdminListResponse
	17, // 20: challenge.SecretsService.AdminAudit:output_type -> challenge.AdminAuditResponse
	19, // 21: challenge.SecretsService.Login:output_type -> challenge.LoginResponse
	12, // [12:22] is the sub-list for method output_type
	2,  // [2:12] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_challenge_proto_init() }
func file_proto_challenge_proto_init() {
	if File_proto_challenge_proto != nil {
		return
	}
	file_proto_challenge_proto_msgTypes[4].OneofWrappers = []any{
		(*ListRequest_ByTag)(nil),
		(*ListRequest_OwnerId)(nil),
	}
	file_proto_challenge_proto_msgTypes[8].OneofWrappers = []any{
		(*UpdateDocRequest_Content)(nil),
		(*UpdateDocRequest_Title)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_challenge_proto_rawDesc), len(file_proto_challenge_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_challenge_proto_goTypes,
		DependencyIndexes: file_proto_challenge_proto_depIdxs,
		MessageInfos:      file_proto_challenge_proto_msgTypes,
	}.Build()
	File_proto_challenge_proto = out.File
	file_proto_challenge_proto_goTypes = nil
	file_proto_challenge_proto_depIdxs = nil
}
